site_name: OpenShift Windows Containers
theme: 
    name: null
    custom_dir: openshift/
    navigation_depth: 1
    include_homepage_in_sidebar: true
    include_search_page: false

extra_css:
    - css/video.css

nav:
- Home: 'index.md'
- Getting Started:
    - 'Getting familiar with the installation': '1-Gettingfamiliar.md'
    - 'Installing The WMCO': '2-InstallingtheWMCO.md'
- Working With The Windows Node:
    - 'Managing a Windows Node': '3-ManagingWindowsNode.md'
    - 'Exploring The Windows Node': '4-ExploringTheWindowsNode.md'
    - 'Running a Windows Container Workload': '5-WindowsContainerWorkload.md'
- NetCandyStore:
    - 'Introduction': 'ns-intro.md'
    - 'Deploying NetCandy Store': '6-ns-deploy.md'
    - 'Exploring NetCandy Store': '7-ns-explore.md'
