name: github pages

on:
  workflow_dispatch:
  push:
    branches: [prod]
    paths-ignore:
      - "README.md"
      - ".gitignore"

permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: gh-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: install mkdocs
        run: pip install mkdocs-material

      - name: build site
        run: mkdocs build

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy github pages
      id: deployment
      uses: actions/deploy-pages@v4
